# Generated by Django 6.0.1 on 2026-01-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_notice_is_approved_notice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
