# Generated by Django 4.2.16 on 2026-02-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_noticereadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticereadstatus',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='notices.notice'),
        ),
    ]
