# Generated by Django 4.2.16 on 2026-02-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_alter_noticereadstatus_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeReadStatus',
        ),
    ]
