# Generated by Django 4.2.16 on 2026-02-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0013_remove_notice_xpires_at_notice_notifications_sent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
