# Generated by Django 4.2.16 on 2026-02-17 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_department',
            field=models.CharField(choices=[('All', 'All Departments'), ('MCA', 'MCA'), ('BTech', 'BTech'), ('MBA', 'MBA')], default='All', max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('MCA', 'MCA'), ('BTech', 'BTech'), ('MBA', 'MBA')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
