# Generated by Django 4.2.16 on 2026-02-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0016_notice_target_department_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('BTech', 'BTech'), ('MBA', 'MBA')], default='MCA', max_length=10),
        ),
    ]
